mkdir data
mkdir data/simulated
mkdir data/labeling
mkdir data/x17
mkdir data/simulated/clean
mkdir data/simulated/noisy
mkdir data/labeling/clean
mkdir data/labeling/noisy
mkdir data/x17/clean
mkdir data/x17/noisy
mkdir data/x17/gauge_backgrounds